#!/usr/bin/env bash
#displays numbers from 1 to 20 and:
#displays bad luck from China for the 4th loop iteration
#displays bad luck from Japan for the 9th loop iteration
#displays bad luck from Italy for the 17th loop iteration
#You must use the while loop (for and until are forbidden)
#You must use the case statement

COUNTER=1
while [  $COUNTER -le 20 ];
do
    echo "$COUNTER"
    case $COUNTER in
    4)
    echo "bad luck from China"
    ;;
    9)
    echo "bad luck from Japan"
    ;;
    17)
    echo "bad luck from Italy"
    ;;
    esac
    let COUNTER+=1
done