#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminate itself when
# receiving a SIGQUIT or SIGTERM signal
trap 'echo I hate the kill command; rm /var/run/myscript.pid; kill -9 $$' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/myscript.pid; kill -9 $$' SIGQUIT
echo $$ | cat > /var/run/myscript.pid
CONDITION=:
while [ $CONDITION ]
do
    echo "To infinity and beyond"
done
