#!/usr/bin/env bash
#displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed
#You must use the for loop (while and until are forbidden)
#Do not display hidden files
LIST="/etc/passwd"
while read i
do
    echo "$i" | cut -d':' -f 1,3,6
done < $LIST