#!/usr/bin/env bash
# Write a Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# Requirement:
# Format: IP HTTP_CODE
# in a list format
# You must use awk
# You are not allowed to use while, for, until and cut
# Download and commit the apache-access.log file along with your answers files
awk '{print $1 " " $9}' apache-access.log